# Generated by Django 5.1.1 on 2024-11-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_phone_number_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, default="XXXXXXXXXX", max_length=10, null=True
            ),
        ),
    ]
