# Generated by Django 5.1.1 on 2024-11-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publiccomplaint",
            name="complaint_status_choice",
            field=models.CharField(
                choices=[
                    ("Investigating", "Investigating"),
                    ("Under review", "Under review"),
                    ("Resolved", "Resolved"),
                    ("Action Taken", "Action Taken"),
                ],
                max_length=15,
            ),
        ),
    ]
